"""
Turns the JSON analysis into a beautiful Markdown report and optionally emails it.
"""

import os
import json
import smtplib
import logging
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

logger = logging.getLogger(__name__)

PRIORITY_EMOJI = {"P1": "🔴", "P2": "🟡", "P3": "🟢"}
SENTIMENT_EMOJI = {"positive": "🟢", "neutral": "⚪️", "negative": "🔴", "mixed": "🟡"}


def _section(title: str) -> str:
    return f"\n## {title}\n"


def build_markdown(analysis: dict, report_date: str) -> str:
    lines = [
        f"# Pocketly Weekly Social Intelligence Report",
        f"**Week ending:** {report_date}  |  "
        f"**Posts analysed:** {analysis.get('posts_analysed', '—')}",
        "",
    ]

    if "error" in analysis:
        lines.append(f"> ⚠️ {analysis['error']}")
        return "\n".join(lines)

    # Executive summary
    lines.append(_section("Executive Summary"))
    lines.append(f"> {analysis.get('executive_summary', '')}")

    # Week score
    ws = analysis.get("week_score", {})
    lines.append(_section("Week at a Glance"))
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Sentiment score | {ws.get('overall_sentiment_score', '—')} / 10 |")
    lines.append(f"| Buzz volume | {ws.get('buzz_volume', '—')} |")
    flags = ws.get("risk_flags", [])
    lines.append(f"| Risk flags | {', '.join(flags) if flags else 'None'} |")

    # Action items (most important — front-loaded)
    lines.append(_section("Action Items"))
    for item in analysis.get("action_items", []):
        emoji = PRIORITY_EMOJI.get(item.get("priority", "P3"), "⚪")
        lines.append(
            f"**{emoji} [{item.get('priority')}] [{item.get('team')}]** "
            f"{item.get('action')}  \n"
            f"  *Why now:* {item.get('rationale')}  "
            f"  *Effort:* {item.get('effort')}\n"
        )

    # Brand mentions
    bm = analysis.get("brand_mentions", {})
    pocketly = bm.get("pocketly", {})
    lines.append(_section("Pocketly Brand Mentions"))
    sent_emoji = SENTIMENT_EMOJI.get(pocketly.get("sentiment", "neutral"), "⚪")
    lines.append(
        f"**Count:** {pocketly.get('count', 0)}  |  "
        f"**Sentiment:** {sent_emoji} {pocketly.get('sentiment', '—')}"
    )
    if pocketly.get("key_themes"):
        lines.append(f"\n**Key themes:** {', '.join(pocketly['key_themes'])}")
    for q in pocketly.get("notable_quotes", []):
        lines.append(f'\n> “{q}”')

    # Competitor snapshot
    lines.append(_section("Competitor Snapshot"))
    for comp in bm.get("competitors", []):
        sent_emoji = SENTIMENT_EMOJI.get(comp.get("sentiment", "neutral"), "⚪")
        lines.append(
            f"### {comp.get('name')}  {sent_emoji}  "
            f"({comp.get('count', 0)} mentions, {comp.get('sentiment')})"
        )
        loves = comp.get("what_users_love", [])
        hates = comp.get("what_users_hate", [])
        if loves:
            lines.append(f"**What users love:** {'; '.join(loves)}")
        if hates:
            lines.append(f"**What users hate:** {'; '.join(hates)}")
        lines.append("")

    # User pain points
    lines.append(_section("User Pain Points & Opportunities"))
    for pp in analysis.get("user_pain_points", []):
        lines.append(f"**{pp.get('pain_point')}** *(frequency: {pp.get('frequency')})*")
        lines.append('> "' + pp.get('verbatim', '') + '"')
        lines.append(f"💡 *Opportunity:* {pp.get('opportunity_for_pocketly', '')}\n")

    # Competitor weaknesses
    lines.append(_section("Competitor Weaknesses to Exploit"))
    for cw in analysis.get("competitor_weaknesses", []):
        lines.append(
            f"**{cw.get('competitor')} — {cw.get('weakness')}**  \n"
            f"> {cw.get('evidence', '')}  \n"
            f"🎯 *Action:* {cw.get('how_pocketly_can_exploit', '')}\n"
        )

    # Emerging trends
    lines.append(_section("Emerging Trends"))
    for trend in analysis.get("emerging_trends", []):
        lines.append(f"**{trend.get('trend')}**  \n{trend.get('description', '')}")
        lines.append(f"📌 *For Pocketly:* {trend.get('pocketly_implication', '')}\n")

    # Content opportunities
    lines.append(_section("Content & Community Engagement Opportunities"))
    for co in analysis.get("content_opportunities", []):
        url = co.get("thread_url") or ""
        link = f"[View thread]({url})" if url else ""
        lines.append(
            f"- **{co.get('platform')}** {link}  \n"
            f"  {co.get('suggested_response_angle', '')}\n"
        )

    lines.append("\n---\n*Generated by Pocketly Social Listener — powered by Claude AI*")
    return "\n".join(lines)


def save_report(markdown: str, output_dir: str = "reports") -> Path:
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    date_str = datetime.now().strftime("%Y-%m-%d")
    path = Path(output_dir) / f"pocketly_social_report_{date_str}.md"
    path.write_text(markdown, encoding="utf-8")
    logger.info("Report saved to %s", path)
    return path


def save_raw_json(analysis: dict, output_dir: str = "reports") -> Path:
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    date_str = datetime.now().strftime("%Y-%m-%d")
    path = Path(output_dir) / f"pocketly_social_raw_{date_str}.json"
    path.write_text(json.dumps(analysis, indent=2), encoding="utf-8")
    return path


def email_report(markdown: str, subject: str) -> bool:
    """Send the report via SMTP if env vars are configured."""
    smtp_host = os.getenv("SMTP_HOST")
    if not smtp_host:
        logger.info("No SMTP_HOST set — skipping email delivery")
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = os.environ["SMTP_USER"]
    msg["To"] = os.environ["REPORT_TO"]
    msg.attach(MIMEText(markdown, "plain"))

    with smtplib.SMTP(smtp_host, int(os.getenv("SMTP_PORT", "587"))) as server:
        server.starttls()
        server.login(os.environ["SMTP_USER"], os.environ["SMTP_PASS"])
        server.sendmail(msg["From"], [msg["To"]], msg.as_string())

    logger.info("Report emailed to %s", msg["To"])
    return True
